"""add_file_hash

Revision ID: 7e81aac35f3e
Revises: 1cce46bd50ae
Create Date: 2026-02-25 04:09:19.414201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e81aac35f3e'
down_revision: Union[str, Sequence[str], None] = '1cce46bd50ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('file_hash', sa.String(), nullable=True))
    op.create_index(op.f('ix_document_file_hash'), 'document', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_file_hash'), table_name='document')
    op.drop_column('document', 'file_hash')
    # ### end Alembic commands ###
